# Generated by Django 3.1.4 on 2021-01-11 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('banner', models.FileField(upload_to='Iamges')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
