# Generated by Django 3.1.4 on 2021-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='banner',
            field=models.FileField(upload_to='Images'),
        ),
    ]
